rootProject.name = "jverify-collection"
include("javaTypesGenerator")
include("common")
include("javac-plugin")
include("javac-plugin-test")
include("verifier")
include("library")
include("builtin-contracts")
include("examples")
include("test-engine")
include("library-for-testing")