dafnyVersion=4.10.1
dafnyRef=f5ca47b85f9af29721646ea517b69088c52bd385
dafnyPrerelease=nightly-2025-05-24-f5ca47b
# If false, dafnyPrerelease can be used to download and install
buildDafnyFromSource=false
