dafnyVersion=4.10.1
dafnyRef=11e26125d184fa93fb0c04c3bea509d53ce8ade7
dafnyPrerelease=nightly-2025-05-24-f5ca47b
# If false, dafnyPrerelease can be used to download and install
buildDafnyFromSource=true
