dafnyVersion=4.10.1
dafnyRef=b9a0256813cce51b359a050ef8cd224f6d2feba0
dafnyPrerelease=nightly-2025-05-24-f5ca47b
# If false, dafnyPrerelease can be used to download and install
buildDafnyFromSource=true
