[book]
language = "en"
multilingual = false
src = "src"
title = "JVerify Tutorial and Reference"

[rust]
edition = "2025"

[output.html]
curly-quotes = true

[output.html.playground]
runnable = false
