import org.gradle.kotlin.dsl.register

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // Use Maven Local for JVerify dependencies since they are not published anywhere yet.
    mavenLocal()
}

dependencies {
    // Depend on the library for specification annotations and methods
    implementation("com.aws.jverify:library:1.0-SNAPSHOT")
    // Depend on the verifier as a build tool
    // TODO: Figure out correct dependency type, and declare the verifier's correctly
    implementation("com.aws.jverify:verifier:1.0-SNAPSHOT")
    // Depend on the annotation processor to erase specification code when building
    annotationProcessor("com.aws.jverify:javac-plugin:1.0-SNAPSHOT")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

fun createJavacExports(targets: List<String>): List<String> {
    val javacPackages = listOf(
        "jdk.compiler/com.sun.tools.javac.api",
        "jdk.compiler/com.sun.tools.javac.file",
        "jdk.compiler/com.sun.tools.javac.util",
        "jdk.compiler/com.sun.tools.javac.tree",
        "jdk.compiler/com.sun.tools.javac.code",
        "jdk.compiler/com.sun.tools.javac.parser",
        "jdk.compiler/com.sun.tools.javac.jvm",
        "jdk.compiler/com.sun.tools.javac.comp",
        "jdk.compiler/com.sun.tools.javac.model",
        "jdk.compiler/com.sun.tools.javac.processing",
        "jdk.compiler/com.sun.tools.javac.main"
    )

    return javacPackages.flatMap { pkg ->
        targets.map { target ->
            "--add-exports=$pkg=$target"
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


tasks.register<JavaExec>("verify") {
    classpath(
        configurations.runtimeClasspath
    )
    mainClass = "com.aws.jverify.verifier.Main"

    jvmArgs = createJavacExports(listOf("ALL-UNNAMED"))
    args(
        "src/main/java/org/example/App.java",
        "--jar",
        sourceSets["main"].runtimeClasspath.filter {
            it.toString().endsWith(".jar")
        }.asPath
    )
}
