/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.aws.jverify.JVerify;

public class App {
    public void DoStuff() {
        JVerify.check(false);
    }
}
