/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var s3Builder = S3Client.builder();
        var s3 = s3Builder.build();

        var builder = ListBucketsRequest.builder();
        builder = builder.maxBuckets(0);
        var request = builder.build();
        var response = s3.listBuckets(request);
//                     ^^^^^^^^^^^^^^^^^^^^^^^ Error: a precondition for this call could not be proved
    }
}

//region Generate-able from the S3 Smithy model (but I hand-wrote it for the demo :)

@SmithyGenerated
@Contract
abstract class S3ClientContract implements S3Client {
    static S3ClientBuilder builder() {
        throw new ContractException();
    }

    public CreateBucketResponse createBucket(CreateBucketRequest createBucketRequest) {
        throw new ContractException();
    }

    @Override
    public ListBucketsResponse listBuckets(ListBucketsRequest listBucketsRequest) throws AwsServiceException, SdkClientException {
        // @range(1, 1000)
        precondition(
            implies(listBucketsRequest.maxBuckets() != null,
                1 <= listBucketsRequest.maxBuckets() && listBucketsRequest.maxBuckets() <= 1000));

        throw new ContractException();
    }

    @Override
    public PutObjectResponse putObject(PutObjectRequest putObjectRequest, RequestBody requestBody) throws AwsServiceException, SdkClientException {
//        precondition(
//                "CRC32".equals(putObjectRequest.checksumAlgorithmAsString())
//                        ? putObjectRequest.checksumCRC32() != null
//                        : putObjectRequest.checksumCRC32() == null);

        return S3Client.super.putObject(putObjectRequest, requestBody);
    }
}

@SmithyGenerated
@Contract
@Modifiable
abstract class SdkBuilderContract<B extends SdkBuilder<B, T>, T> implements SdkBuilder<B, T> {

    T building;

    @Override
    public T build() {
        postcondition((T result) -> result == building);

        throw new ContractException();
    }
}

@Contract(ListBucketsRequest.class)
@SmithyGenerated
class ListBucketsRequestContract {
    public static ListBucketsRequest.Builder builder() {
        postcondition((ListBucketsRequestBuilderContract result) ->
                fresh(result) && result.building.maxBuckets() == null);

        throw new ContractException();
    }

    @Pure
    public @Nullable Integer maxBuckets() {
        reads(this);

        throw new ContractException();
    }
}

@Contract(ListBucketsRequest.Builder.class)
@SmithyGenerated
abstract class ListBucketsRequestBuilderContract
        extends SdkBuilderContract<ListBucketsRequest.Builder, ListBucketsRequest>
        implements ListBucketsRequest.Builder {

    @Override
    public ListBucketsRequest.Builder maxBuckets(Integer maxBuckets) {
        modifies(this);
        postcondition(Integers.equal(this.building.maxBuckets(), maxBuckets));
        postcondition((ListBucketsRequest.Builder result) -> result == this);

        throw new ContractException();
    }
}


@Contract(PutObjectRequest.class)
@SmithyGenerated
class PutObjectRequestContract {
    public static PutObjectRequest.Builder builder() {
        postcondition((PutObjectRequestBuilderContract result) ->
                fresh(result)
                    && result.building.checksumAlgorithmAsString() == null
                    && result.building.checksumCRC32() == null);

        throw new ContractException();
    }

    @Pure
    public @Nullable Integer checksumAlgorithm() {
        reads(this);

        throw new ContractException();
    }

    @Pure
    public @Nullable String checksumAlgorithmAsString() {
        reads(this);

        throw new ContractException();
    }

    @Pure
    public @Nullable String checksumCRC32() {
        reads(this);

        throw new ContractException();
    }
}

@Contract(PutObjectRequest.Builder.class)
@SmithyGenerated
abstract class PutObjectRequestBuilderContract
        extends SdkBuilderContract<PutObjectRequest.Builder, PutObjectRequest>
        implements PutObjectRequest.Builder {

    @Override
    public PutObjectRequest.Builder checksumAlgorithm(ChecksumAlgorithm checksumAlgorithm) {
        modifies(this);
        postcondition(this.building.checksumAlgorithm() == checksumAlgorithm);
        postcondition((PutObjectRequest.Builder result) -> result == this);

        throw new ContractException();
    }
}

// Working around complexities in modelling the top-level Object.equals()
class Integers {
    @Pure
    public static boolean equal(@Nullable Integer a, @Nullable Integer b) {
        return a == null ? b == null : b != null && a.intValue() == b.intValue();
    }
}
//class Objects {
//    @Pure
//    public static boolean equal(@Nullable Object a, @Nullable Object b) {
//        return a == null ? b == null : b != null && a.equals(b);
//    }
//}

//endregion
