name: PR build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  merge_group:

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
  
jobs:
  checks:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2019 ]
        include:
          - os: ubuntu-22.04
            chmod: true
          - os: windows-2019
            chmod: false
      fail-fast: false
        
    runs-on: ${{ matrix.os }}

    env:
      z3BaseUri: https://github.com/dafny-lang/solver-builds/releases/download/snapshot-2024-04-10

    steps:
      - uses: actions/checkout@v4
        with:
          path: jverify-collection
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'
          cache: gradle
      - name: Build Dafny
        working-directory: ./jverify-collection/dafny
        run: |
          dotnet build ./Source/Dafny.sln
      - name: Download Z3
        shell: pwsh
        working-directory: ./jverify-collection/dafny
        run: |
          Invoke-WebRequest ${{env.z3BaseUri}}/z3-4.12.1-x64-${{matrix.os}}-bin.zip -OutFile z3.zip
          Expand-Archive z3.zip .
          Remove-Item z3.zip
          mkdir -p Binaries/z3/bin
          mv z3-* Binaries/z3/bin/
      - name: Set Z3 permissions
        if: ${{matrix.chmod}}
        working-directory: ./jverify-collection/dafny
        run: |
          chmod +x Binaries/z3/bin/z3*
      - name: Code generation has no diff
        working-directory: ./jverify-collection
        run: |
          make test-generation-nodiff
      - name: Gradle test
        working-directory: ./jverify-collection
        run: |
          ./gradlew test --info
      - name: Publish packages locally
        working-directory: ./jverify-collection
        run: |
          ./gradlew publishToMavenLocal
      - name: Sample project
        working-directory: ./jverify-collection/sample-project
        run: |
          ./gradlew test --info