name: PR build

on:
  workflow_dispatch:
  pull_request:
  merge_group:

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
  
jobs:
  checks:
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-2022 ]
        include:
          - os: ubuntu-24.04
            chmod: true
          - os: windows-2022
            chmod: false
      fail-fast: false
        
    runs-on: ${{ matrix.os }}

    env:
      z3BaseUri: https://github.com/dafny-lang/solver-builds/releases/download/snapshot-2024-04-10

    steps:
      - uses: actions/checkout@v4
        with:
          path: jverify-collection
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'
          cache: gradle
      - name: Build Strata
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory:
            ./jverify-collection/Strata
          build: "true"
          test: "false"
          lint: "false"
      - name: Add Lake to path (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Add-Content $env:GITHUB_PATH "$HOME/.elan/bin"
      - name: Install z3 on PATH
        shell: bash
        run: |
          ARCH=$(uname -m)
          if [ "$OS" = "Windows_NT" ] || [ "$OS" = "MINGW"* ]; then
            ARCHIVE_NAME="z3-4.15.2-x64-win"
            curl -L -o z3.zip https://github.com/Z3Prover/z3/releases/download/z3-4.15.2/z3-4.15.2-x64-win.zip
            unzip z3.zip
          elif [ "$ARCH" = "x86_64" ]; then
            ARCH_NAME="x86_64"
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.15.2/z3-4.15.2-x64-glibc-2.39.zip
            ARCHIVE_NAME="z3-4.15.2-x64-glibc-2.39"
            unzip "${ARCHIVE_NAME}.zip"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi
          chmod +x "${ARCHIVE_NAME}/bin/z3"
          echo "$GITHUB_WORKSPACE/${ARCHIVE_NAME}/bin/" >> $GITHUB_PATH
      - name: Build Dafny
        working-directory: ./jverify-collection/dafny
        run: |
          dotnet build ./Source/Dafny.sln
      - name: Code generation has no diff
        working-directory: ./jverify-collection
        run: |
          make test-generation-nodiff
      - name: Install verifier CLI locally
        working-directory: ./jverify-collection
        run: |
          ./gradlew installDist
      - name: Publish packages locally
        working-directory: ./jverify-collection
        run: |
          ./gradlew publishToMavenLocal
      - name: Getting started command (non-Windows)
        if: runner.os != 'Windows'
        working-directory: ./jverify-collection
        run: |
          ./verifier/build/install/verifier/bin/verifier ./examples/src/test/java/com/aws/jverify/examples/BinarySearch.java --verifier ./dafny/Scripts/dafny --contract-path ./builtin-contracts/build/libs/builtin-contracts-1.0-SNAPSHOT-sources.jar
      - name: Getting started command (Windows)
        if: runner.os == 'Windows'
        working-directory: ./jverify-collection
        run: |
          ./verifier/build/install/verifier/bin/verifier.bat ./examples/src/test/java/com/aws/jverify/examples/BinarySearch.java --verifier ./dafny/Binaries/Dafny.exe --contract-path ./builtin-contracts/build/libs/builtin-contracts-1.0-SNAPSHOT-sources.jar
      - name: Add Dafny to path (non-Windows)
        if: runner.os != 'Windows'
        run: |
          echo "${PWD}/jverify-collection/dafny/Scripts" >> $GITHUB_PATH
      - name: Add Dafny to path (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Add-Content $env:GITHUB_PATH "${PWD}/jverify-collection/dafny/Binaries"
      - name: Verify sample project
        working-directory: ./jverify-collection/sample-project
        shell: bash
        run: |
          ./gradlew verify --info
      - name: Gradle test
        working-directory: ./jverify-collection
        run: |
          ./gradlew test --info
