name: PR build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  merge_group:

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
  
jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: jverify-collection
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle
      - name: Build Dafny 
        run: |
          dotnet build ./jverify-collection/dafny/Source/Dafny.sln
      - name: Code generation has no diff
        working-directory: ./jverify-collection
        run: |
          make test-generation-nodiff
      - name: Gradle test
        working-directory: ./jverify-collection
        run: |
          ./gradlew init test --info